apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadazks6285-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadazks6285-tenant-component
    app.kubernetes.io/part-of: loadazks6285-tenant-app
  name: loadazks6285-tenant-component
  namespace: loadazks6285-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadazks6285-tenant-component
    weight: null
status: {}
